### ISSUE TITLE
[keyman.com] Resizing browser window past certain thresholds breaks menuing

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman.com#117]
I noticed while testing a recent PR that keyman.com's page-width test to determine the menu type to display has an interesting issue if you cross the threshold while the menu is displayed:

![Screen Shot 2020-06-25 at 8 19 54 AM](https://user-images.githubusercontent.com/25213402/85643008-268bed00-b6bd-11ea-98d6-110b78740d48.png)

Just a few pixels wider:

![Screen Shot 2020-06-25 at 8 20 07 AM](https://user-images.githubusercontent.com/25213402/85643020-30155500-b6bd-11ea-9d9f-db6a6af6e269.png)

Also, in this situation, it is impossible to dismiss the menu without shrinking the page again (so that the menu 'hamburger' reappears and can be used for dismissal).  While the 'desktop'-aimed hover menus do appear to function in this state, they aren't very usable - the phone menu hides them.

**Comment by mcdurdin** [comment]
Can you check this against staging? I did some fixes to some of this resizing recently but not sure if I've caught 100% of the issues

**Comment by jahorton** [comment]
It's still a thing.

<img width="1131" alt="Screen Shot 2020-07-08 at 9 19 43 AM" src="https://user-images.githubusercontent.com/25213402/86866989-34e5fa00-c0fc-11ea-97ae-5206ab9a9c4b.png">
<img width="1142" alt="Screen Shot 2020-07-08 at 9 19 51 AM" src="https://user-images.githubusercontent.com/25213402/86867004-3adbdb00-c0fc-11ea-85dc-70a4ecf890f9.png">
