### ISSUE TITLE
[staging] Console exceptions on keyboard install page

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#125]
From embedded keyboard search on the staging site, I'm getting console exceptions with the following:

Chrome mobile viewport (Pixel 2)
1. Go to https://staging-keyman-com.azurewebsites.net/go/android/14.0/download-keyboards
2. Search for "khmer_angkor"
3. On the result page, click on "khmer_angkor"
4. This loads https://staging-keyman-com.azurewebsites.net/keyboards/khmer_angkor but with the console exceptions
```
search.js:282 Uncaught TypeError: Cannot read property 'q' of undefined
    at init (search.js:282)
    at load_search (search.js:311)
```

**Comment by darcywong00** [comment]
Clicking the green button from https://staging-keyman-com.azurewebsites.net/keyboards/install/khmer_angkor
generates a brief console log exception

![install exception](https://user-images.githubusercontent.com/7358010/87494024-412c0300-c678-11ea-9bc9-8e637b9a3322.png)

and the page gets routed to https://staging-keyman-com.azurewebsites.net/keyboards/download?id=khmer_angkor&platform=android&mode=standalone

**Comment by darcywong00** [comment]
Also in Android emulator for API 21 (Android 5.0), the keyboard search results fail to load

![search on 21](https://user-images.githubusercontent.com/7358010/87503067-73942b00-c68d-11ea-8415-e9309b323750.png)

**Comment by mcdurdin** [comment]
Updated URLs for test:
* https://keyman-staging.com/go/android/14.0/download-keyboards
* https://keyman-staging.com/keyboards/khmer_angkor
* https://keyman-staging.com/keyboards/install/khmer_angkor
* https://keyman-staging.com/keyboards/download?id=khmer_angkor&platform=android&mode=standalone

**Comment by mcdurdin** [comment]
@darcywong00 The initial errors reported here are corrected. I note that the landing page (https://keyman-staging.com/keyboards/install/khmer_angkor) for Android is still messy when Keyman is not yet installed...

**Comment by darcywong00** [comment]
> The initial errors reported here are corrected.

On the latest `master` branch with a pixel 2 emulator and API 21, I now get a console exception:
`Uncaught SyntaxError: Unexpected token >   search.js:223`
which is
```
function buildPager(res, q, obsolete) {
  var pager = $('<div class="pager">');
  function appendPager(pager, text, page) {
    if(page != res.context.pageNumber && page > 0 && page <= res.context.totalPages) {
      $('<a>'+text+'</a>').attr('href', getCurrentPath(q, page, obsolete)).click((event) => goToPage(event, q, page)).appendTo(pager);    <!-- this line -->
    } else {
      $('<span>'+text+'</span>').appendTo(pager);
    }
  }
```

A search (like khmer_angkor) briefly gives the exception

![search errors](https://user-images.githubusercontent.com/7358010/93726995-3f843b80-fbe3-11ea-8c16-ed5e8b404b70.png)

The page refreshes, and the second exception disappears. But no results are displayed

**Comment by mcdurdin** [comment]
```
(event) => goToPage(event, q, page)
```

needs to change to:

```
function(event) { return goToPage(event, q, page); }
```

phooey.
