### ISSUE TITLE
[staging] invalid package 'go'-based download links not returning error code

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman.com#128]
For example, try visiting https://staging-keyman-com.azurewebsites.net/go/package/download/foobar?platform=ios&tier=alpha&bcp47=km&update=1.

**What I expected**:  a 404 or similar error code.

**What I got**: "Invalid parameter; id not found" (likely from a PHP error), 'success' HTTP header.

**Comment by mcdurdin** [comment]
Updated URL: https://keyman-staging/go/package/download/foobar?platform=ios&tier=alpha&bcp47=km&update=1

**Comment by mcdurdin** [comment]
This endpoint now correctly returns a 404 (with JSON as content for machine-readability if you really want it) for invalid packages.
