### ISSUE TITLE
chore: Update Windows installer filename references from keymandesktop-a.b.c.d.exe to keyman-a.b.c.exe when we go to stable

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#186]
Right now, the website refers in a few places to keymandesktop-a.b.c.d.exe but we should change the pattern when we go to stable to the new keyman-a.b.c.exe.

At least some of these changes have a TODO against them in the source referencing this issue number #186.

**Comment by darcywong00** [comment]
Done in #250
