### ISSUE TITLE
bug(keyman.com) 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman.com#199]
Three of the buttons in the keyman.com keyboard landing page are shown as "Install" instead of "Download" since they are not installable on the current devices/platforms keyman.com is being browsed on. (See the screenshot below)

![image](https://user-images.githubusercontent.com/28331388/99230746-436abd80-2822-11eb-90f0-3c63615359b2.png)

**Comment by mcdurdin** [comment]
This is resolved on the staging site.

![image](https://user-images.githubusercontent.com/4498365/99350792-4c778f80-28f3-11eb-86b9-d5a633b7b268.png)
