### ISSUE TITLE
bug: Keyboard missing in bookmarklet

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#225]
On keymanweb.com, we can save a bookmarklet for
https://keymanweb.com/#th,Keyboard_basic_kbdth0

But on https://keyman.com/bookmarklet/ (also the staging site), the Basic Thai keyboard doesn't appear in the list of bookmarklets.

![image](https://user-images.githubusercontent.com/7358010/102171081-49f36000-3ec8-11eb-8fb6-f814429c8116.png)

**Comment by mcdurdin** [comment]
Fixed by #237.
