### ISSUE TITLE
staging: Remove localhost from keyboard download link

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#232]
Related to keymanapp/keyman#4247

On an Android device with Keyman for Android 14.0- beta installed,
Opening the external Chrome browser to https://keyman-staging.com/amharic and try to install the amharic keyboard.

The staging site is generating a link 
keyman://localhost/open?keyboard=gff_amharic&language=am

But the app won't download because it needs to match a regex `keyboards/install`

Per @mcdurdin 
> We can always change the website to point to the .kmp, can't we? After release of 14.0 anyway...

We might want the 14.0 app to handle the legacy link though.

**Comment by mcdurdin** [comment]
I think we go with your PR keymanapp/keyman#4292 and leave this one well enough alone. Closing.
