### ISSUE TITLE
bug: eurolatin templating looks duplicated

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#254]
On the staging site, the header and footer for Eurolatin look duplicated
https://keyman-staging.com/keyboards/h/eurolatin/

There's also an extra banner before the keyboard details

## Header(s)
![euro-header](https://user-images.githubusercontent.com/7358010/111725720-26aac900-889a-11eb-8a11-0399bc6b3483.png)

## Footer(s)
![euro-footer](https://user-images.githubusercontent.com/7358010/111725732-2d394080-889a-11eb-8037-3f94771d1e05.png)

**Comment by darcywong00** [comment]
Also, the page has both dynamic and static lists of "Supported Languages"

**Comment by mcdurdin** [comment]
Ref https://github.com/keymanapp/keyboards/pull/1489
