### ISSUE TITLE
bug(search): Searching for German vs Deutsch gives different results

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman.com#285]
Searching for "Deutsch" shows "German Basic" as first keyboard, which has the most downloads, "EuroLatin (SIL)" as second one.

Searching for "German" instead reverses these two, and the order of the following keyboards is also different.

**Comment by mcdurdin** [comment]
I think this is to be expected, because `Deutsch` will match only on the language name, whereas `German` will also match on keyboard name, description and other details.
