### ISSUE TITLE
Broken links when click on the Google results

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman.com#290]
**Description and Repro**
Google for "keyman hotkey" and click on the first two results to see "Page not found". The third link works. 

![image](https://user-images.githubusercontent.com/28331388/113086636-374d2e80-920c-11eb-88e3-7d7822b3a1ab.png)

**Possible Cause**
The uniformity of URLs of the first two links are different from the third.

The first two URLs:
`https://help.keyman.com/products/windows/current-version/docs/start_hotkey_set`
`https://help.keyman.com/products/windows/current-version/docs/basic_hotkeys_tab`

The third URL:
`https://help.keyman.com/products/windows/15.0/start/hotkey_set`

**Possible Solution**
It looks like we want to have `start/hotkey_set` instead of `docs/start_hotkey_set`. The `docs/start_` should have been realized as `/start/`.

**Comment by mcdurdin** [comment]
This now appears to be resolved.
