### ISSUE TITLE
[keyman.com] Some keyboards not listing when searching with language name

### ISSUE THREAD

**Issue by ramesh-k** [keymanapp/keyman.com#30]
Some keyboards tagged with multiple BCP-47 codes are not listing in  https://keyman.com/keyboards when searching with language name. 

For Example, [Malar Braille](https://keyman.com/keyboards/malar_braille) keyboard and [Devanagari Phonetic (SIL)](https://keyman.com/keyboards/sil_devanagari_phonetic) keyboard are [listed](https://keyman.com/keyboards/languages/hi) for language with BCP 47 code 'hi'. But these keyboards are not listing when [searching](https://keyman.com/keyboards?q=Hindi) for language name 'Hindi'.

**Comment by LornaSIL** [comment]
@mcdurdin @jahorton I've verified this to be true. Where does this issue belong?

**Comment by mcdurdin** [comment]
This is an appropriate place for this issue. We will be addressing these issues as part of our language search refresh. The issue arises, I think, because Malar Braille is registered with `hi-Brai` and thus the website is not matching it with the BCP 47 code `hi`.

**Comment by mcdurdin** [comment]
Complete in staging.
