### ISSUE TITLE
12.0 release prep

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman.com#34]
I did a scan through the site and found the following things that we should consider addressing for release:

- keyman.com/desktop/features 
    - [x] shows an 11.0 splash under "easy setup"
    - [x] "Technical Support" - shows some version info
    - [x] "Used by Biggest" - should we really be showing SIL as a big-name user now?
    - [x] The CSS seems a bit off at the top
- keyman.com/desktop
    - [x] final Q - add "11.0" mention
- keyman.com/developer
    - [x] CTRL+F 'respository'
- keyman.com/developer/features
    - [x] Same CSS thing as /desktop/features
    - [x] First left-hand menu jump target is off
    - [x] Broken links to bcp47-tags
- keyman.com/mac 
    - [ ] are the known issues still current?
- keyman.com/linux
    - Q:  install a Keyman keyboard
        - [x] Issue:  help.keyman.com link is wrong.  Missing a /guide/ in the path!
- keyman.com/iphone-and-ipad
    - [x] Should we still keep the "now free" bit?
    - [x] Second link from bottom - iphone instead of iPhone.
    - [x] Version history link is off.
- keyman.com/android
    - [x] Version history link again.
- keyman.com/downloads/archive
    - [x] Will need to add last stable 11.0 versions here
- keyman.com/testimonials
    - [x] Most recent testimonial is from mid-2012.  Yikes.

The issues noted with the CSS above also affect (at minimum) the current 11.0 version of the pages.

**Comment by mcdurdin** [comment]
Another thing for release:

- [ ] prominent banner for donating to Keyman linked to release.
