### ISSUE TITLE
Do keyboard queries by country require `id` or not?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#344]
While working on #339 and testing keyboard queries by country

I saw the keyboard search page says
> For example c:thailand searches for keyboards for languages used in Thailand.

But the web.config is inserting **id**
https://github.com/keymanapp/keyman.com/blob/4736eb9f685fb24096907cbf5f832bc630bb2460/web.config#L159-L162

https://keyman.com/keyboards/countries/thailand returns 0 results

https://keyman.com/keyboards?q=c%3Athailand returns several results

Whichever way this should be, we should update the .htaccess file accordingly

**Comment by mcdurdin** [comment]
I think this is `c:id:th` for a country code search, or `c:thailand` for a string search.

**Comment by mcdurdin** [comment]
https://keyman.com/keyboards/countries/th and https://keyman.com/keyboards?q=c%3Athailand are correct.
