### ISSUE TITLE
chore: upgrade to Google Analytics 4

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#347]
Per email:

> We'll soon sunset Universal Analytics
> 
> On 1 July 2023, Universal Analytics will stop processing new hits. If you still rely on Universal Analytics, we urge you to prepare for the future by completing your move to Google Analytics 4, our next-generation measurement solution.

**Comment by darcywong00** [comment]
[Migration  guide](https://support.google.com/analytics/answer/10089681?hl=en&ref_topic=12154439,12153943,2986333,&visit_id=638148810669543333-189299568&rd=1)

**Comment by darcywong00** [comment]
Should we just remove GA a la keymanapp/help.keyman.com#722 and keymanapp/keymanweb.com#73?
