### ISSUE TITLE
Pre-release page out of date?

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman.com#386]
Keyman 16 .0.141 is listed as stable here https://keyman.com/downloads/ which makes sense.
![image](https://github.com/keymanapp/keyman.com/assets/986339/82f0a0aa-049d-49aa-99ed-928e5f8fb4bd)

Keyman 16.0.136 is listed as beta here and 17 is listed as Alpha here: https://keyman.com/downloads/pre-release/ 
![image](https://github.com/keymanapp/keyman.com/assets/986339/54aaa077-d2df-4aa2-bf79-436adc56a838)

Shouldn't 17 be the beta right now and the 16.0.136 be only in previous versions? I think something got stuck on this page.

**Comment by darcywong00** [comment]
Currently, our development cycle (master branch [TIER](https://github.com/keymanapp/keyman/blob/master/TIER.md)) is in 17.0 alpha. Thus, the nightly builds are 17.0 alpha.

And the most recent beta was 16.0.136 before 16.0 became the stable release.
