### ISSUE TITLE
[keyman.com] Update references to tavultesoft infrastructure

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#4]
Eventually, links to tavultesoft infrastructure will need to be removed.

Some of them are:
- [x] Several featured keyboards redirect to tavulesoft
- [x] downloads/archive/ references self-service manual activation

more to be added later...

**Comment by mcdurdin** [comment]
Note: link to manual self-service activation still works. It's bare bones but that's fine for the limited use case. Closing as complete.
