### ISSUE TITLE
chore: strip out the ingress for staging from production

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#426]
- [ ] https://github.com/keymanapp/site-kubernetes-config/blob/main/production/api.keyman.com/patch/networking.yaml
  - [ ] https://github.com/keymanapp/site-kubernetes-config/blob/main/production/help.keyman.com/patch/networking.yaml
  - [ ] https://github.com/keymanapp/site-kubernetes-config/blob/main/production/keyman.com/patch/networking.yaml
  - [ ] https://github.com/keymanapp/site-kubernetes-config/blob/main/production/keymanweb.com/patch/networking.yaml
  - [ ] https://github.com/keymanapp/site-kubernetes-config/blob/main/production/s.keyman.com/patch/networking.yaml

**Comment by darcywong00** [comment]
I think @tim-eves completed this in keymanapp/site-kubernetes-config#43, right?

**Comment by mcdurdin** [comment]
> I think @tim-eves completed this in [keymanapp/site-kubernetes-config#43](https://github.com/keymanapp/site-kubernetes-config/pull/43), right?

I think so, yes.

**Comment by mcdurdin** [comment]
Done.
