### ISSUE TITLE
bug: Mobile layout of /developer/features is suboptimal

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#432]
@LornaSIL reports the page is terrible on her phone
> The margins keep me from seeing the text without scrolling left and right

https://keyman.com/developer/features

**Comment by darcywong00** [comment]
I wonder if we shouldn't bother with the left panel on phone layout. Would also need a "download" section at the very bottom after Comprehensive Help

**Comment by Meng-Heng** [comment]
This update should fix this issue now #434 🤞🏻
