### ISSUE TITLE
chore: update Keyman Developer download to refer to kmc instead of kmcomp

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#433]
Do we need to add to keyman.com? Currently, that page has kmcomp.

_Originally posted by @darcywong00 in https://github.com/keymanapp/help.keyman.com/pull/1057#discussion_r1503413372_

We should also have a note about "where has kmcomp gone"

**Comment by darcywong00** [comment]
Do we also want a link in /downloads/archive to the last 16.0 stable kmcomp?

**Comment by mcdurdin** [comment]
> Do we also want a link in /downloads/archive to the last 16.0 stable kmcomp?

Good idea

**Comment by darcywong00** [comment]
Since this depends on 17.0 release, I'll bump this to A18S1

**Comment by mcdurdin** [comment]
Can we put it B17S6 instead? Because that is in theory the week we'll be doing the release.
