### ISSUE TITLE
onboard-keyman

### ISSUE THREAD

**Issue by abudulamh** [keymanapp/keyman.com#450]
It no longer works after the update
Fedora 40 gnome 46
Manjaro Gnome 46
cachyos Gnome 46

**Comment by darcywong00** [comment]
Hi @abudulamh - Can you provide some more details on what no longer works in onboard-keyman?
* Does the OSK not display?
* Does selecting keys not work?
* Does the OSK not match the current Keyman keyboard?

Also can you tell us what version of Keyman you're using?

We currently don't have capacity to maintain onboard-keyman, and on the [Keyman roadmap](https://blog.keyman.com/2023/09/keyman-roadmap-september-2023), we aim to replace it with a new OSK in Keyman 19.0

**Comment by mcdurdin** [comment]
Can we move this support query to https://community.software.sil.org/c/keyman, where we will be better able to support you? This repository is for the keyman.com. website, so it's not the right place for this.
