### ISSUE TITLE
bug: Help link is being displayed on keyboard page even when there is no help file

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman.com#459]
In the past, and even now, when a page doesn't have a help file it would say `Help not available.` which is absolutely correct.
![image](https://github.com/keymanapp/keyman.com/assets/7071907/d926bdd9-066f-49fc-81bf-41a1017b5299)

See: https://keyman.com/keyboards/armenian

We recently incorrectly accepted the `way` keyboard where the `help` folder was in the root rather than the `source` folder:
https://github.com/keymanapp/keyboards/tree/master/release/w/way

On this page, it has a link to the help file:
https://keyman.com/keyboards/way

![image](https://github.com/keymanapp/keyman.com/assets/7071907/2a715433-fcdd-40a5-bee3-8653a4551376)

But that link doesn't work so it just reverts to https://help.keyman.com/keyboard/

It should say `Help not available` until we get the help in the correct location.

**Comment by DavidLRowe** [comment]
https://github.com/keymanapp/keyboards/pull/2842 will move the help file into the proper place, but we are waiting to merge it until this bug has been investigated.

**Comment by mcdurdin** [comment]
The link to the help file is determined by the `helpLink` property of the .keyboard_info (or .kps) file. The website does not attempt to test the validity of the link. At this stage, we won't try and address this; we do get reports of broken links which we can chase when we have the energy.

```
"helpLink": "https://help.keyman.com/keyboard/way"
```
