### ISSUE TITLE
chore: update SIL logo on keyman.com and other sites

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#460]
https://sites.google.com/sil.org/brand-resource-center/branding/visual-brand/logos

When we do so, let's make it a lot smaller than it currently is

**Comment by darcywong00** [comment]
Would it rotate through the 5 glyph options, or just pick one?

The updated logo also applies to the Keyman apps

**Comment by mcdurdin** [comment]
> Would it rotate through the 5 glyph options, or just pick one?

Let's keep it simple and just pick one (happy if you want to upload the other graphics to the site though)

**Comment by mcdurdin** [comment]
> Let's keep it simple and just pick one (happy if you want to upload the other graphics to the site though)

Changed my mind -- it is pretty straightforward to implement (in PHP probably) to render one of 5 images.

* @Meng-Heng can you connect with @darcywong00 on making this update?
* @sgschantz I have added this project to @Meng-Heng's task list :)

**Comment by Meng-Heng** [comment]
Of course, @mcdurdin! I will see what I can do.

**Comment by darcywong00** [comment]
Keeping this open for rest of websites to update
