### ISSUE TITLE
chore: build.sh --debug should not build the CDN

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#470]
When building for local development, we want to be able to use the --debug flag so that the CDN is not used and we read directly from /cdn/dev instead of /cdn/deploy for resources such as images and stylesheets.

This means that build.sh start should not build the CDN at all, because if the file is missing, it'll be read from /cdn/dev as a fallback.

**Comment by mcdurdin** [comment]
@darcywong00 are you able to do this one? It'll make local site development a lot nicer!

**Comment by darcywong00** [comment]
atm, some tricky interaction

The websites generate CDN during `/resources/init-container.sh`

And the bootstrapper `_common/docker.inc.sh` will call `resources/init-container.sh` if it exists.

On help.keyman.com, we still want init-container.sh to generate keyboard cache - just not CDN.

**Comment by mcdurdin** [comment]
Yes, the flag will need to bubble down into init-container, at this point, only CDN should be left alone.

(Or you could make the `./build.sh build --debug` script _remove_ the deploy folder after the container is init ... which is kinda ugly but would have the same outcome)
