### ISSUE TITLE
bug: Stable url for keyboard download no longer works

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman.com#474]
Our sldr files use this form of url to reference a keyboard, but it just goes to the home page for the keyboard:
https://keyman.com/go/keyboard/sil_euro_latin/download/kmp

This one works: https://keyman.com/go/package/download/sil_euro_latin

However, @mcdurdin says the first one is recommended and the second one is not a publicly stable one. 

This is possibly a bug coming out of our move to Docker with Apache recently.

**Comment by darcywong00** [comment]
Preliminary investigation:

Original IIS rule
https://github.com/keymanapp/keyman.com/blob/ab3d0a4dfcb1915a9dafd10e2d98fff0a90b4d03/go/web.config#L21-L25

Current .htaccess rule
https://github.com/keymanapp/keyman.com/blob/b695ba05961de47b25ba38ba3a210a232b09f615/go/.htaccess#L10-L11

Seems both go to `/keyboards/download?id=$1&platform=windows&mode=standalone`

Will check if that's supposed to load a page or redirect to a kmp file
