### ISSUE TITLE
bug: PHP sentry reports for test environment are getting labeled as `production`

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#476]
https://keyman.sentry.io/issues/5872955114/events/88aae080bb674c53a0abd7857b62a9b7/

using broken-link-checker/0.7.8 Node.js/18.20.4 (Linux 5.15; x64)

e.g. http://localhost:8053/14/keyman-engine-changes should be being labeled as `test` not `production`

**Comment by darcywong00** [comment]
I think fixed by keymanapp/shared-sites#35
