### ISSUE TITLE
[keyman.com] User request for keyboard page to display list of associated BCP 47 language tags 

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#6]
@sewhite writes 
> Would it be possible to have the page describing a keyboard display or have a link to the list of language tags that the keyboard is valid for? For instance, Lorna just pasted a link to the github repo listing the BCP 47 tags for the Libtralo keyboard. Could this link be on the keyboard description page?

From https://community.software.sil.org/t/suggestion-for-keyman-keyboard-listings/1196

--------------

I (Darcy) wonder if we can add it to the "Keyboard Details" section in `keyboards/keyboard.php`.

**Comment by mcdurdin** [comment]
With 14.0 release, this will list the language names. Language codes are available with a tooltip when hovering on the language name. See https://keyman-staging.com/keyboards/sil_euro_latin#expand-languages for the pre-release site.
