### ISSUE TITLE
[keyman.com] Keyman search for languages

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman.com#7]
We are getting inconsistent results when searching for languages.

If we search for a language name, like "Tagalog", we see "Tagalog" showing up.
![image1](https://user-images.githubusercontent.com/7071907/44545101-bafc2180-a6d9-11e8-8848-7e64564a2667.png)

If we search for a language code, like "tgl", see the language name PLUS a dialect name (like "Tagalog (Bataan)"). This is undesirable as the iso code does not actually refer to a specific dialect. In this case, it's just using the first dialect alphabetically and is not based on most common dialect at all. 
![dhhbahaomddjdfnh](https://user-images.githubusercontent.com/7071907/44545139-da934a00-a6d9-11e8-8e1e-fe10bd8e84b0.png)

My view: I'm assuming you are using a list from the Ethnologue and it's finding the first dialect alphabetically. I wonder if we should be using a different list of just the languages -- and not
the dialects. Since we cannot select a dialect in Keyman, I don't think we should display the dialects on keyman.com.

However, I realize there are competing requirements.

**Comment by mcdurdin** [comment]
Sorta related and thrown here so we tackle it together with the other bits and pieces: we should normalize and remove diacritics for the search, e.g. Haiɫzaqvla as compared to Haíɫzaqvḷa and Hailzaqvla (ref https://community.software.sil.org/t/firstvoices-keyboard-app-no-longer-displaying-long-press-characters-with-ios-update/3289/2)

**Comment by mcdurdin** [comment]
Complete in staging.
