### ISSUE TITLE
[keyman.com] Show deprecation information in the keyboard search results

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#8]
@markpenny would like to see deprecation info on keyboard search results to help users make a better decision which keyboard to install. (e.g. which [SIL IPA](https://keyman.com/keyboards?q=sil+ipa) keyboard to get?)

Direction from @mcdurdin 
>  The search currently doesn't publish deprecation information in the search results but it does in the individual keyboard information. Two possible fixes:
>
>1. Show a 'deprecated' flag next to deprecated keyboards. What should that deprecated flag be? Probably a red box next to the title says something like [ Old version, replaced by _sil_ipa_ ], and clicking the red box would take you to the new keyboard.
>2. Don't show deprecated keyboards by default.
>
>I think the 'deprecated' flag is actually better because if people are searching for a familiar keyboard, or if the only result shown is for a deprecated keyboard, navigation to the replacement becomes clear.
>
>Obv we don't use the term 'deprecated' in the UI because it's a weird word for many users.

2. is related to #177

**Comment by darcywong00** [comment]
The revamped keyboard search appears to have resolved this.
From https://keyman-staging.com/keyboards/sil_euro_latin

european and european2 are marked **(deprecated)**.

Also, deprecated keyboards are filtered out of keyboard searches 
(https://keyman-staging.com/keyboards?q=european2 yields 0 results)

**Comment by mcdurdin** [comment]
https://keyman-staging.com/downloads/archive/ contains a link to search for deprecated (aka obsolete) keyboards: `https://keyman-staging.com/keyboards?q=&page=1&obsolete=1`

That search provides results for both obsolete and current keyboards. By default, the search does not show obsolete keyboards.
